spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/parsons_data_db
    username: root
    password: Xia13752715579!
    driver-class-name: com.mysql.cj.jdbc.Driver
    
  main:
    web-application-type: servlet
mybatis:
  type-aliases-package: com.parsons.pojo
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath*:mappers/*.xml
server:
  port: 8080