spring:
  datasource:
    url: jdbc:mysql://localhost:3306/parsons_data_db
    username: root
    password: 843215yg
    driver-class-name: com.mysql.cj.jdbc.Driver
  mybatis:
    mapper-locations: classpath*:mappers/*.xml
    type-aliases-package: com.parsons.pojo
    configuration:
      map-underscore-to-camel-case: true
  server:
    port: 8080
  main:
    web-application-type: servlet

