spring:
  datasource:
    url: jdbc:mysql://localhost:3306/parsons_data_db
    username: root
    password: gy001213
    driver-class-name: com.mysql.cj.jdbc.Driver
  main:
    web-application-type: servlet
mybatis:
  type-aliases-package: com.parsons.pojo
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath*:mappers/*.xml
server:
  port: 8080

